apiVersion: apps/V1
kind: Deployment
metadata:
  name: mysql
  namespace: cluster-managed-apps
  labels:
    app: mysql
    tier: backend
spec:
  selector:
   matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
      containers:
      - name: mysql
        image: mysql:5.7.29
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 200m
            memory: 500Mi
          limits:
            cpu: 250m
            memory: 750Mi  
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: pv-mysql
        envFrom:
        - configMapRef:
            name: mysql-cm
    volumes:
    - name: pv-mysql
      persistentVolumeClaim:
        claimName: pvc-mysql